# This file is part of the ddd-symfony package.
#
# (c) Beñat Espiña <benatespina@gmail.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

homepage:
    pattern: /
    defaults:
        _controller: 'AppBundle:Default:index'
